eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: consumer-user
  zipkin:
    base-url: http://localhost:9441
server:
  port: 9002
feign:
  hystrix:
    enabled: true