server:
  port: 7001

#eureka实例名，集群中根据这里相互识别
eureka:
  instance:
    hostname: eureka1
#客户端
  client:
    #是否开启注册服务，true表示自己注册自己
    register-with-eureka: false
    #是否拉取服务列表，这里只提供服务给别的服务
    fetch-registry: false
    #注册中心地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
